### ISSUE TITLE
The problem of finetune the model jmodt.pth

### ISSUE THREAD

**Issue by Cimy-wang** [Kemo-Huang/JMODT#5]
![image](https://user-images.githubusercontent.com/54029375/137630906-fd54b67d-f0d1-489a-ae9e-d579e1cc95bb.png)

I think the optimizer.pth of model jomdt.pth is needed to finetune it.

**Comment by Kemo-Huang** [comment]
Finetuning does not need to load optimizer. I think I have already set `cfg.TRAIN.RELOAD_OPTIMIZER = False` in the "jmodt/config.py" file.
