### ISSUE TITLE
 Hello, where can I find these txt files? Or how do I need to create it? thanks！！

### ISSUE THREAD

**Issue by ferrari700** [Kemo-Huang/JMODT#6]
![235397](https://user-images.githubusercontent.com/72401926/137833263-dcd8b4b6-5725-4567-a450-7d3c39249eb3.jpg)

**Comment by saesaria** [comment]
@ferrari700 have you found the files? I also looking for the files and not found yet.

**Comment by Kemo-Huang** [comment]
You can create these files via `python tools/kitti_converter.py --data_root ${DATA_ROOT}` as mentioned in README.md
