### ISSUE TITLE
 How to generate the three files test.txt, sample2frame.txt and seq2sample.txt?

### ISSUE THREAD

**Issue by ferrari700** [Kemo-Huang/JMODT#7]
By modifying kitti_converter.py, I can only generate the three files in the picture below. Excuse me, test.txt, sample2frame.txt and seq2sample.txt, how to generate these three files? thank you very much！！

![image](https://user-images.githubusercontent.com/72401926/140741791-2c0aeae0-8f6c-4702-99a7-e80322150c96.png)

**Comment by wangxiyang2022** [comment]
Hello, I want to ask you that did you have solved this problem?

**Comment by Kemo-Huang** [comment]
Now the codes for converting the test dataset are available.
